# Generated by Django 3.0.5 on 2020-04-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_frozen'),
    ]

    operations = [
        migrations.AddField(
            model_name='dairyproduct',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='frozen',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fruitsandvegetable',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='other',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pastrie',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readymeal',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='snack',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='softdrink',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
