# Generated by Django 3.0.5 on 2020-05-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200430_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FW', 'Fruits and Vegetables'), ('P', 'Pastry'), ('S', 'Snack'), ('RM', 'Ready Meal'), ('DP', 'Dairy Product'), ('SD', 'Soft Drink'), ('FG', 'Frozen Good')], default='FW', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
